version: 0.2

phases:
  install:
    commands:
      - echo start [Development branch]
      - echo Insatlling NPM Packages and wget Enviorment File
      - npm install -g pnpm@6
  pre_build:
    commands:
      - pnpm install -no-frozen-lockfile
  build:
    commands:
      - echo pnpm build start `date`
      - NODE_OPTIONS="--max-old-space-size=6144" pnpm build:dev
  post_build:
    commands:
      - ls -al
      - echo Copy mywellnesslab Build File
      - aws s3 cp --recursive dist/ s3://mywellnesslab.dev.amway.co.kr
      - echo Build completed on `date`